name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.FLARE_CITY_TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.FLARE_CITY_TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup - node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup - yarn
        run: |
          yarn config set npmScopes.flare-city.npmAuthToken "\${NPM_TOKEN}"

      - name: Install dependencies
        run: yarn --immutable

      - name: Packages - build
        run: yarn build
