name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    env:
      TURBO_TOKEN: ${{ secrets.FLARE_CITY_TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.FLARE_CITY_TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: yarn install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: Version packages"
          commit: "chore: Version packages"
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.FLARE_CITY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.FLARE_CITY_NPM }}
