name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    env:
      TURBO_TOKEN: ${{ secrets.FLARE_CITY_TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.FLARE_CITY_TURBO_TEAM }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Setup Yarn v4
        run: |
          yarn config set npmScopes.npmAuthToken "\${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.FLARE_CITY_NPM }}

      - name: Install dependencies
        run: yarn  --immutable

      - name: Packages - build
        run: yarn build

      - name: Packages - version
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: Version packages"
          commit: "chore: Version packages"
          version: yarn version # version so pnp can reconcile packages
          publish: yarn pusblish # build and publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.FLARE_CITY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.FLARE_CITY_NPM }}

      - name: Packages - tag
        # if: steps.changesets.outputs.hasChangesets == 'false'
        # You can do something when a publish should happen.
        run: yarn tag
